version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: "mysql:5.7"
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=Block2School
    ports:
      - "3306:3306"
    expose:
      - 3306

  b2c-server:
    build: .
    image: b2c-server
    depends_on:
      - mysql
    ports: 
      - '8080:8080'