name: Deployment
on:
  push:
    branches:
      - production

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.SERVER_IP }}
      key: ${{ secrets.SSH_KEY }}
      username: ${{ secrets.SERVER_USERNAME }}
      password: ${{ secrets.SERVER_PASSWORD }}
      port: 22
      script: |
        cd ~/back/
        git pull origin production
